// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Picklr.Models;

#nullable disable

namespace Picklr.Migrations
{
    [DbContext(typeof(PicklrContext))]
    [Migration("20260626170612_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Picklr.Models.AppUser", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "alice@picklr.com",
                            FirstName = "Alice",
                            LastName = "Smith",
                            Role = "Admin"
                        },
                        new
                        {
                            UserID = 2,
                            Email = "bob@picklr.com",
                            FirstName = "Bob",
                            LastName = "Jones",
                            Role = "Client"
                        });
                });

            modelBuilder.Entity("Picklr.Models.Club", b =>
                {
                    b.Property<int>("ClubID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClubID");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            ClubID = 1,
                            Description = "Our flagship downtown club with 10 indoor courts.",
                            Location = "123 Main St, Chicago, IL",
                            Name = "Picklr Downtown"
                        },
                        new
                        {
                            ClubID = 2,
                            Description = "A vibrant outdoor facility with 8 courts and a pro shop.",
                            Location = "456 Oak Ave, Evanston, IL",
                            Name = "Picklr Northside"
                        });
                });

            modelBuilder.Entity("Picklr.Models.PicklProgram", b =>
                {
                    b.Property<int>("ProgramID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fee")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProgramID");

                    b.ToTable("Programs");

                    b.HasData(
                        new
                        {
                            ProgramID = 1,
                            Description = "Drop-in open play for new players. No experience needed.",
                            Fee = 10.00m,
                            Name = "Beginner Open Play"
                        },
                        new
                        {
                            ProgramID = 2,
                            Description = "Weekly skill-building clinic led by a certified coach.",
                            Fee = 25.00m,
                            Name = "Intermediate Clinic"
                        },
                        new
                        {
                            ProgramID = 3,
                            Description = "Competitive round-robin tournament for rated players.",
                            Fee = 40.00m,
                            Name = "Advanced Tournament"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
