using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace Picklr.Models
{
    // Named PicklProgram to avoid a name collision with the top-level Program class
    // generated by .NET's top-level statements feature.
    public class PicklProgram
    {
        [Key]
        public int ProgramID { get; set; }

        [Required(ErrorMessage = "Please enter a program name.")]
        public string Name { get; set; } = string.Empty;

        public string Description { get; set; } = string.Empty;

        [Range(0, 10000, ErrorMessage = "Fee must be between 0 and 10000.")]
        public decimal Fee { get; set; }

        // Foreign key to Club (Phase 2)
        [Required(ErrorMessage = "Please select a club.")]
        [Display(Name = "Club")]
        public int ClubID { get; set; }

        // Navigation property. [ValidateNever] because the Club object itself
        // is never posted from a form -- only ClubID is (same technique the
        // Murach ToDo List sample, Ch10, used for Category/Status).
        [ValidateNever]
        public Club Club { get; set; } = null!;

        // Comma-separated list of day names, e.g. "Monday,Wednesday,Friday".
        // Stored as one delimited string column -- the same technique the
        // Filters class (Ch10, slide 42) used for "category-due-status",
        // instead of adding a separate join table for something this small.
        [Display(Name = "Available Days")]
        public string AvailableDays { get; set; } = string.Empty;

        // Convenience (read-only) property: turns "Monday,Wednesday,Friday"
        // into a List<string> the views/controller can loop over or check.
        public List<string> AvailableDayList =>
            string.IsNullOrWhiteSpace(AvailableDays)
                ? new List<string>()
                : AvailableDays.Split(',', StringSplitOptions.RemoveEmptyEntries).ToList();

        // For display in the admin table, e.g. "Monday, Wednesday, Friday"
        public string AvailableDaysDisplay => string.Join(", ", AvailableDayList);

        // Used by the public search page to check whether this program
        // runs on a given calendar date's day of the week.
        public bool IsAvailableOn(DateTime date) =>
            AvailableDayList.Contains(date.DayOfWeek.ToString());
    }
}
